<?php

$base = '/admin/merchandising-trace';

return [
    [
        'group_title' => '',
        [
            'title'      => 'Merchandising',
            'icon'       => 'fa-solid fa-shirt',
            'icon_color' => 'text-primary',
            'permission' => '',
            'order'      => 13,
            'children'   => [
                [
                    'title'      => 'Dashboard',
                    'icon'       => 'fa-solid fa-gauge',
                    'icon_color' => 'text-primary',
                    'permission' => 'merch_dashboard',
                    'route'      => "$base/dashboard",
                ],
                [
                    'title'      => 'Master Data',
                    'icon'       => 'fa-solid fa-gear',
                    'icon_color' => 'text-secondary',
                    'permission' => '',
                    'children'   => [
                        ['title' => 'Buyers', 'icon' => 'fa-solid fa-handshake', 'icon_color' => 'text-info', 'permission' => 'merch_buyer', 'route' => "$base/buyers"],
                        ['title' => 'Seasons', 'icon' => 'fa-solid fa-snowflake', 'icon_color' => 'text-info', 'permission' => 'merch_season', 'route' => "$base/seasons"],
                        ['title' => 'Product Types', 'icon' => 'fa-solid fa-shapes', 'icon_color' => 'text-info', 'permission' => 'merch_product_type', 'route' => "$base/product-types"],
                        ['title' => 'Colors', 'icon' => 'fa-solid fa-palette', 'icon_color' => 'text-info', 'permission' => 'merch_color', 'route' => "$base/colors"],
                        ['title' => 'Sizes', 'icon' => 'fa-solid fa-ruler-combined', 'icon_color' => 'text-info', 'permission' => 'merch_size', 'route' => "$base/sizes"],
                        ['title' => 'Wash Types', 'icon' => 'fa-solid fa-soap', 'icon_color' => 'text-info', 'permission' => 'merch_wash_type', 'route' => "$base/wash-types"],
                        ['title' => 'Ship Modes', 'icon' => 'fa-solid fa-plane-departure', 'icon_color' => 'text-info', 'permission' => 'merch_ship_mode', 'route' => "$base/ship-modes"],
                        ['title' => 'Factories', 'icon' => 'fa-solid fa-industry', 'icon_color' => 'text-info', 'permission' => 'merch_factory', 'route' => "$base/factories"],
                        ['title' => 'Suppliers', 'icon' => 'fa-solid fa-truck-field', 'icon_color' => 'text-info', 'permission' => 'merch_supplier', 'route' => "$base/suppliers"],
                        ['title' => 'Currencies', 'icon' => 'fa-solid fa-money-bill', 'icon_color' => 'text-info', 'permission' => 'merch_currency', 'route' => "$base/currencies"],
                        ['title' => 'Item Categories', 'icon' => 'fa-solid fa-layer-group', 'icon_color' => 'text-info', 'permission' => 'merch_item_category', 'route' => "$base/item-categories"],
                        ['title' => 'Items (BOM Library)', 'icon' => 'fa-solid fa-boxes-stacked', 'icon_color' => 'text-info', 'permission' => 'merch_item', 'route' => "$base/items"],
                        ['title' => 'Unit of Measure', 'icon' => 'fa-solid fa-ruler', 'icon_color' => 'text-info', 'permission' => 'merch_uom', 'route' => "$base/uoms"],
                        ['title' => 'Departments', 'icon' => 'fa-solid fa-sitemap', 'icon_color' => 'text-info', 'permission' => 'merch_department', 'route' => "$base/departments"],
                        ['title' => 'Style Image Types', 'icon' => 'fa-solid fa-image', 'icon_color' => 'text-info', 'permission' => 'merch_style_image_type', 'route' => "$base/style-image-types"],
                        ['title' => 'Sample Types', 'icon' => 'fa-solid fa-list-ol', 'icon_color' => 'text-info', 'permission' => 'merch_sample_type', 'route' => "$base/sample-types"],
                    ],
                ],
                [
                    'title'      => 'Dev (R&D)',
                    'icon'       => 'fa-solid fa-flask',
                    'icon_color' => 'text-warning',
                    'permission' => '',
                    'children'   => [
                        ['title' => 'Inquiries', 'icon' => 'fa-solid fa-magnifying-glass-dollar', 'icon_color' => 'text-warning', 'permission' => 'merch_inquiry', 'route' => "$base/inquiries"],
                        ['title' => 'Tech Pack / Styles', 'icon' => 'fa-solid fa-vest-patches', 'icon_color' => 'text-warning', 'permission' => 'merch_style', 'route' => "$base/styles"],
                        ['title' => 'Risk Assessment', 'icon' => 'fa-solid fa-triangle-exclamation', 'icon_color' => 'text-warning', 'permission' => 'merch_risk_assessment', 'route' => "$base/risk-assessments"],
                        ['title' => 'Costing (Pre-order)', 'icon' => 'fa-solid fa-calculator', 'icon_color' => 'text-warning', 'permission' => 'merch_costing', 'route' => "$base/cost-sheets"],
                    ],
                ],
                [
                    'title'      => 'Order + BOM',
                    'icon'       => 'fa-solid fa-file-signature',
                    'icon_color' => 'text-danger',
                    'permission' => '',
                    'children'   => [
                        ['title' => 'Sales Contracts', 'icon' => 'fa-solid fa-file-signature', 'icon_color' => 'text-danger', 'permission' => 'merch_sales_contract', 'route' => "$base/sales-contracts"],
                        ['title' => 'BOM', 'icon' => 'fa-solid fa-list-check', 'icon_color' => 'text-danger', 'permission' => 'merch_bom', 'route' => "$base/boms"],
                        ['title' => 'Fabric & Accessories Booking', 'icon' => 'fa-solid fa-boxes-packing', 'icon_color' => 'text-danger', 'permission' => 'merch_material_booking', 'route' => "$base/material-bookings"],
                    ],
                ],
                [
                    'title'      => 'Sample Stages & Approvals',
                    'icon'       => 'fa-solid fa-vial',
                    'icon_color' => 'text-danger',
                    'permission' => 'merch_sample',
                    'route'      => "$base/samples",
                ],
                [
                    'title'      => 'T&A (Time & Action)',
                    'icon'       => 'fa-solid fa-calendar-check',
                    'icon_color' => 'text-primary',
                    'permission' => '',
                    'children'   => [
                        ['title' => 'T&A Plans', 'icon' => 'fa-solid fa-calendar-check', 'icon_color' => 'text-primary', 'permission' => 'merch_tna', 'route' => "$base/tna-plans"],
                        ['title' => 'T&A Grid', 'icon' => 'fa-solid fa-table-cells-large', 'icon_color' => 'text-primary', 'permission' => 'merch_tna', 'route' => "$base/tna-plans-grid"],
                        ['title' => 'T&A Templates', 'icon' => 'fa-solid fa-table-list', 'icon_color' => 'text-primary', 'permission' => 'merch_tna', 'route' => "$base/tna-templates"],
                        ['title' => 'T&A Alerts', 'icon' => 'fa-solid fa-bell', 'icon_color' => 'text-primary', 'permission' => 'merch_tna', 'route' => "$base/tna-alerts"],
                        ['title' => 'Sub-T&A', 'icon' => 'fa-solid fa-diagram-project', 'icon_color' => 'text-primary', 'permission' => 'merch_tna', 'route' => "$base/tna-sub-plans"],
                    ],
                ],
                [
                    'title'      => 'Handover to Production',
                    'icon'       => 'fa-solid fa-right-left',
                    'icon_color' => 'text-success',
                    'permission' => 'merch_production_handover',
                    'route'      => "$base/production-handovers",
                ],
                [
                    'title'      => 'Production Tracking',
                    'icon'       => 'fa-solid fa-diagram-project',
                    'icon_color' => 'text-success',
                    'permission' => '',
                    'children'   => [
                        ['title' => 'Shipment Plan', 'icon' => 'fa-solid fa-ship', 'icon_color' => 'text-success', 'permission' => 'merch_shipment_plan', 'route' => "$base/shipment-plans"],
                        ['title' => 'Buyer Communication', 'icon' => 'fa-solid fa-comments', 'icon_color' => 'text-success', 'permission' => 'merch_communication', 'route' => "$base/communication-logs"],
                    ],
                ],
                [
                    'title'      => 'Reports',
                    'icon'       => 'fa-solid fa-file-invoice',
                    'icon_color' => 'text-primary',
                    'permission' => '',
                    'children'   => [
                        ['title' => 'All Reports', 'icon' => 'fa-solid fa-list', 'icon_color' => 'text-primary', 'permission' => 'merch_reports', 'route' => "$base/reports"],
                        ['title' => 'T&A Status Report', 'icon' => 'fa-solid fa-calendar-check', 'icon_color' => 'text-primary', 'permission' => 'merch_reports', 'route' => "$base/reports/tna_status"],
                        ['title' => 'PCD Pass/Fail Analysis', 'icon' => 'fa-solid fa-flag-checkered', 'icon_color' => 'text-primary', 'permission' => 'merch_reports', 'route' => "$base/reports/pcd_analysis"],
                        ['title' => 'Sample Status & Turnaround', 'icon' => 'fa-solid fa-vial', 'icon_color' => 'text-primary', 'permission' => 'merch_reports', 'route' => "$base/reports/sample_turnaround"],
                        ['title' => 'Fabric & Trims In-House', 'icon' => 'fa-solid fa-boxes-stacked', 'icon_color' => 'text-primary', 'permission' => 'merch_reports', 'route' => "$base/reports/fabric_trims_in_house"],
                        ['title' => 'Costing Summary & Margin', 'icon' => 'fa-solid fa-calculator', 'icon_color' => 'text-primary', 'permission' => 'merch_reports', 'route' => "$base/reports/costing_summary"],
                        ['title' => 'Order Book & Value', 'icon' => 'fa-solid fa-book', 'icon_color' => 'text-primary', 'permission' => 'merch_reports', 'route' => "$base/reports/order_book"],
                        ['title' => 'Delay Analysis', 'icon' => 'fa-solid fa-hourglass-half', 'icon_color' => 'text-primary', 'permission' => 'merch_reports', 'route' => "$base/reports/delay_analysis"],
                        ['title' => 'Sub-T&A Send/Receive', 'icon' => 'fa-solid fa-diagram-project', 'icon_color' => 'text-primary', 'permission' => 'merch_reports', 'route' => "$base/reports/sub_tna"],
                        ['title' => 'Shipment Plan vs Actual', 'icon' => 'fa-solid fa-ship', 'icon_color' => 'text-primary', 'permission' => 'merch_reports', 'route' => "$base/reports/shipment_plan_vs_actual"],
                        ['title' => 'Buyer Scorecard', 'icon' => 'fa-solid fa-star', 'icon_color' => 'text-primary', 'permission' => 'merch_reports', 'route' => "$base/reports/buyer_scorecard"],
                        ['title' => 'Merchandiser Workload', 'icon' => 'fa-solid fa-user-clock', 'icon_color' => 'text-primary', 'permission' => 'merch_reports', 'route' => "$base/reports/merchandiser_workload"],
                        ['title' => 'Order Profitability', 'icon' => 'fa-solid fa-sack-dollar', 'icon_color' => 'text-primary', 'permission' => 'merch_reports', 'route' => "$base/reports/order_profitability"],
                        ['title' => 'Document Compliance', 'icon' => 'fa-solid fa-file-shield', 'icon_color' => 'text-primary', 'permission' => 'merch_reports', 'route' => "$base/reports/document_compliance"],
                    ],
                ],
            ],
        ],
    ],
];
